name: dbt CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dbt
        run: |
          pip install dbt-snowflake

      - name: Create dbt profile
        run: |
          mkdir -p ~/.dbt
          echo "
          nyc_etl_dbt:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                user: ${{ secrets.SNOWFLAKE_USER }}
                password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                role: ${{ secrets.SNOWFLAKE_ROLE }}
                warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
                database: ${{ secrets.SNOWFLAKE_DATABASE }}
                schema: SILVER
                threads: 1
          " > ~/.dbt/profiles.yml

      - name: Run dbt models
        run: |
          cd nyc_etl_dbt
          dbt run

      - name: Run dbt tests
        run: |
          cd nyc_etl_dbt
          dbt test